// Source: https://azure.microsoft.com/en-us/global-infrastructure/services/

var locations = [
    'usgovvirginia',
    'usgoviowa',
    'usgovtexas',
    'usgovarizona',
    'usdodeast',
    'usdodcentral'
];

module.exports = {
    all: locations,
    resources: locations,
    storageAccounts: ['global'],
    virtualMachines: locations,
    snapshots: locations,
    disks: locations,
    activityLogAlerts: ['global'],
    vaults: locations,
    policyAssignments: locations.concat(['global']),
    recoveryServiceVaults: locations,
    backupPolicies: locations,
    backupProtectedItems: locations,
    webApps: locations,
    appServiceCertificates: locations,
    networkSecurityGroups: locations,
    servers: locations,
    logProfiles: ['global'],
    profiles: ['global'],
    managementLocks: ['global'],
    blobServices: locations,
    networkWatchers: locations,
    networkInterfaces: locations,
    managedClusters: locations,
    virtualMachineScaleSets: locations,
    autoProvisioningSettings: ['global'],
    securityContacts: ['global'],
    usages: ['global'],
    subscriptions: ['global'],
    loadBalancers: locations,
    availabilitySets: locations,
    virtualNetworks: locations,
    virtualNetworkPeerings: locations,
    virtualNetworkGateways: locations,
    networkGatewayConnections: locations,
    natGateways: locations,
    users: ['global'],
    registries: locations,
    redisCaches: locations,
    pricings: ['global'],
    roleDefinitions: ['global'],
    aad: ['global'],
    groups: ['global'],
    servicePrincipals: ['global'],
    autoscaleSettings: locations,
    resourceGroups: locations,
    policyDefinitions: locations,
    diagnosticSettingsOperations: ['global'],
    databaseAccounts: locations,
    securityCenter: ['global'],
    advisor: ['global'],
    publicIPAddresses: locations,
    privateDnsZones: ['global'],
    privateEndpoints: locations,
    securityContactv2: ['global'],
    images: locations,
    vmScaleSet: locations,
    applicationGateway: locations,
    wafPolicies: locations,
    routeTables: locations,
    bastionHosts: locations,
    applications: ['global'],
    eventGrid: locations,
    eventHub: locations,
    mediaServices: locations,
    serviceBus: locations,
    classicFrontDoors: ['global'],
    afdWafPolicies: ['global'],
    appConfigurations: locations,
    automationAccounts: locations,
    openAI: locations,
    logAnalytics: locations,
    publicIpAddresses: locations,
    computeGalleries: locations,
    databricks: locations,
    containerApps: locations,
    synapse: locations,
};
