// Source: https://azure.microsoft.com/en-us/global-infrastructure/services/

var locations = [
    'eastasia',
    'southeastasia',
    'centralus',
    'eastus',
    'eastus2',
    'westus',
    'northcentralus',
    'southcentralus',
    'northeurope',
    'westeurope',
    'japanwest',
    'japaneast',
    'brazilsouth',
    'australiaeast',
    'australiasoutheast',
    'southindia',
    'centralindia',
    'westindia',
    'canadacentral',
    'canadaeast',
    'uksouth',
    'ukwest',
    'westcentralus',
    'westus2',
    'koreacentral',
    'koreasouth',
    'francecentral',
    'francesouth',
    'australiacentral',
    'australiacentral2',
    'southafricanorth',
    'southafricawest',
    'global'
];

module.exports = {
    all: locations,
    resources: locations,
    resourceGroups: locations,
    storageAccounts: locations,
    BlobService: locations,
    FileService: locations,
    QueueService: locations,
    TableService: locations,
    virtualMachines: locations,
    disks: locations,
    virtualMachineExtensions: locations,
    autoscaleSettings: locations,
    activityLogAlerts: ['global'],
    vaults: locations,
    KeyVaultClient: locations,
    blobContainers: locations,
    policyAssignments: locations,
    policyDefinitions: locations,
    webApps: locations,
    networkSecurityGroups: locations,
    servers: {
        locations,
        mysql: locations,
        sql: locations,
    },
    autoscaleSettings: locations,
    encryptionProtectors: locations,
    logProfiles: locations,
    profiles: locations,
    endpoints: locations,
    origins: locations,
    diagnosticSettingsOperations: {
        locations,
        nsg: locations
    },
    transparentDataEncryptions: locations,
    databases: locations,
    policyDefinitions: locations,
    autoscaleSettings: locations,
    diagnosticSettingsOperations: {
        locations,
        nsg: locations
    },
    serverBlobAuditingPolicies: locations,
    serverSecurityAlertPolicies: locations
};